### THIS FILE IS NOT TO BE EDITED CASUALLY. IF AT ALL THERE ARE ANY CHANGES, MAKE THE SIMILAR CHANGES IN ALL OTHER BOTS AND ON ADMIN DASHBOARD LAMBDA FUNCTION FILE AS WELL. ###
### NEW COURSE CAN BE ADDED BUT NEED TO ADD ALL INFORMATION IN ALL FILES ###
### KEYS in KEY VALUE PAIR IN COURSES_DETAILS IS NOT TO BE CHANGED LIGHTLY SINCE IT'S BEING USED IN LAMBDA FUNCTION AS WELL ###
### In course_content file, the THIS_COURSE_ID and THIS_COURSE_NAME and LAST_LEVEL are being fetched from this file ###

COURSES_NAMES = {
    1: 'Python Basic',
    2: 'Python Advanced',
    3: 'Machine Learning Basic',
    4: 'Machine Learning Advanced',
    5: 'NLP Basic',
    6: 'NLP Advanced',
    7: 'Computer Vision Basic',
    8: 'Computer Vision Advanced',
    9: 'Deep Learning Basic',
    10: 'Deep Learning Advanced',
    11: 'Devops Basic',
    12: 'Devops Advanced',
    13: 'Blockchain For All',
    14: 'Web3 Basic',
    15: 'Web3 Advanced',
    16: 'AI 2023 For All',
    17: 'AI Tools Basic',
    18: 'AI Tools Advanced',
    19: 'Mind Management',
}


COURSES_DETAILS = {
    'pb': {
        'course_id': 1,
        'course_name': 'Python Basic',
        'course_slug': 'python-basic',
        'allusers_path': '/pb/users',
        'user_path': '/pb/user/{userid}',
        'certificates_requested_path': '/pb/certificates-requested',
        'certificates_generated_path': '/pb/certificates-generated',
        'generate_certificate_path': '/pb/user/{userid}/generate-certificate',
        'certificate_bucket': 'pb-certificate-bucket',
        'levels': 12,
        'blank_certificate_location': 'certificate_format/python_basic_blank_certificate.png'
    },
    'pa': {
        'course_id': 2,
        'course_name': 'Python Advanced',
        'course_slug': 'python-advanced',
        'allusers_path': '/pa/users',
        'user_path': '/pa/user/{userid}',
        'certificates_requested_path': '/pa/certificates-requested',
        'certificates_generated_path': '/pa/certificates-generated',
        'generate_certificate_path': '/pa/user/{userid}/generate-certificate',
        'certificate_bucket': 'pa-certificate-bucket',
        'levels': 19,
        'blank_certificate_location': 'certificate_format/python_advanced_blank_certificate.png'
    },
    'mlb': {
        'course_id': 3,
        'course_name': 'Machine Learning Basic',
        'course_slug': 'machine-learning-basic',
        'allusers_path': '/mlb/users',
        'user_path': '/mlb/user/{userid}',
        'certificates_requested_path': '/mlb/certificates-requested',
        'certificates_generated_path': '/mlb/certificates-generated',
        'generate_certificate_path': '/mlb/user/{userid}/generate-certificate',
        'certificate_bucket': 'mlb-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/ml_basic_blank_certificate.png'
    },
    'mla': {
        'course_id': 4,
        'course_name': 'Machine Learning Advanced',
        'course_slug': 'machine-learning-advanced',
        'allusers_path': '/mla/users',
        'user_path': '/mla/user/{userid}',
        'certificates_requested_path': '/mla/certificates-requested',
        'certificates_generated_path': '/mla/certificates-generated',
        'generate_certificate_path': '/mla/user/{userid}/generate-certificate',
        'certificate_bucket': 'mla-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/ml_advanced_blank_certificate.png'
    },
    'nlpb': {
        'course_id': 5,
        'course_name': 'NLP Basic',
        'course_slug': 'nlp-basic',
        'allusers_path': '/nlpb/users',
        'user_path': '/nlpb/user/{userid}',
        'certificates_requested_path': '/nlpb/certificates-requested',
        'certificates_generated_path': '/nlpb/certificates-generated',
        'generate_certificate_path': '/nlpb/user/{userid}/generate-certificate',
        'certificate_bucket': 'nlpb-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/nlp_basic_blank_certificate.png'
    },
    'nlpa': {
        'course_id': 6,
        'course_name': 'NLP Advanced',
        'course_slug': 'nlp-advanced',
        'allusers_path': '/nlpa/users',
        'user_path': '/nlpa/user/{userid}',
        'certificates_requested_path': '/nlpa/certificates-requested',
        'certificates_generated_path': '/nlpa/certificates-generated',
        'generate_certificate_path': '/nlpa/user/{userid}/generate-certificate',
        'certificate_bucket': 'nlpa-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/nlp_advanced_blank_certificate.png'
    },
    'cvb': {
        'course_id': 7,
        'course_name': 'Computer Vision Basic',
        'course_slug': 'computer-vision-basic',
        'allusers_path': '/cvb/users',
        'user_path': '/cvb/user/{userid}',
        'certificates_requested_path': '/cvb/certificates-requested',
        'certificates_generated_path': '/cvb/certificates-generated',
        'generate_certificate_path': '/cvb/user/{userid}/generate-certificate',
        'certificate_bucket': 'cvb-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/cv_basic_blank_certificate.png'
    },
    'cva': {
        'course_id': 8,
        'course_name': 'Computer Vision Advanced',
        'course_slug': 'computer-vision-advanced',
        'allusers_path': '/cva/users',
        'user_path': '/cva/user/{userid}',
        'certificates_requested_path': '/cva/certificates-requested',
        'certificates_generated_path': '/cva/certificates-generated',
        'generate_certificate_path': '/cva/user/{userid}/generate-certificate',
        'certificate_bucket': 'cva-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/cv_advanced_blank_certificate.png'
    },
    'dlb': {
        'course_id': 9,
        'course_name': 'Deep Learning Basic',
        'course_slug': 'deep-learning-basic',
        'allusers_path': '/dlb/users',
        'user_path': '/dlb/user/{userid}',
        'certificates_requested_path': '/dlb/certificates-requested',
        'certificates_generated_path': '/dlb/certificates-generated',
        'generate_certificate_path': '/dlb/user/{userid}/generate-certificate',
        'certificate_bucket': 'dlb-certificate-bucket',
        'levels': 10,
        'blank_certificate_location': 'certificate_format/deeplearning_basic_blank_certificate.png'
    },
    'dla': {
        'course_id': 10,
        'course_name': 'Deep Learning Advanced',
        'course_slug': 'deep-learning-advanced',
        'allusers_path': '/dla/users',
        'user_path': '/dla/user/{userid}',
        'certificates_requested_path': '/dla/certificates-requested',
        'certificates_generated_path': '/dla/certificates-generated',
        'generate_certificate_path': '/dla/user/{userid}/generate-certificate',
        'certificate_bucket': 'dla-certificate-bucket',
        'levels': 8,
        'blank_certificate_location': 'certificate_format/deeplearning_advanced_blank_certificate.png'
    },
    'dopsb': {
        'course_id': 11,
        'course_name': 'Devops Basic',
        'course_slug': 'devops-basic',
        'allusers_path': '/dopsb/users',
        'user_path': '/dopsb/user/{userid}',
        'certificates_requested_path': '/dopsb/certificates-requested',
        'certificates_generated_path': '/dopsb/certificates-generated',
        'generate_certificate_path': '/dopsb/user/{userid}/generate-certificate',
        'certificate_bucket': 'dopsb-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/devops_basic_blank_certificate.png'
    },
    'dopsa': {
        'course_id': 12,
        'course_name': 'Devops Advanced',
        'course_slug': 'devops-advanced',
        'allusers_path': '/dopsa/users',
        'user_path': '/dopsa/user/{userid}',
        'certificates_requested_path': '/dopsa/certificates-requested',
        'certificates_generated_path': '/dopsa/certificates-generated',
        'generate_certificate_path': '/dopsa/user/{userid}/generate-certificate',
        'certificate_bucket': 'dopsa-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/devops_advanced_blank_certificate.png'
    },
    'bforall': {
        'course_id': 13,
        'course_name': 'Blockchain For All',
        'course_slug': 'blockchain-for-all',
        'allusers_path': '/bforall/users',
        'user_path': '/bforall/user/{userid}',
        'certificates_requested_path': '/bforall/certificates-requested',
        'certificates_generated_path': '/bforall/certificates-generated',
        'generate_certificate_path': '/bforall/user/{userid}/generate-certificate',
        'certificate_bucket': 'bforall-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/blockchainforall_blank_certificate.png'
    },
    'web3b': {
        'course_id': 14,
        'course_name': 'Web3 Basic',
        'course_slug': 'web3-basic',
        'allusers_path': '/web3b/users',
        'user_path': '/web3b/user/{userid}',
        'certificates_requested_path': '/web3b/certificates-requested',
        'certificates_generated_path': '/web3b/certificates-generated',
        'generate_certificate_path': '/web3b/user/{userid}/generate-certificate',
        'certificate_bucket': 'web3b-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/web3_basic_blank_certificate.png'
    },
    'web3a': {
        'course_id': 15,
        'course_name': 'Web3 Advanced',
        'course_slug': 'web3-advanced',
        'allusers_path': '/web3a/users',
        'user_path': '/web3a/user/{userid}',
        'certificates_requested_path': '/web3a/certificates-requested',
        'certificates_generated_path': '/web3a/certificates-generated',
        'generate_certificate_path': '/web3a/user/{userid}/generate-certificate',
        'certificate_bucket': 'web3a-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/web3_advanced_blank_certificate.png'
    },
    'aiforall': {
        'course_id': 16,
        'course_name': 'AI For All',
        'course_slug': 'ai-for-all',
        'allusers_path': '/aiforall/users',
        'user_path': '/aiforall/user/{userid}',
        'certificates_requested_path': '/aiforall/certificates-requested',
        'certificates_generated_path': '/aiforall/certificates-generated',
        'generate_certificate_path': '/aiforall/user/{userid}/generate-certificate',
        'certificate_bucket': 'aiforall-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/aiforall_blank_certificate.png'
    },
    'aitb': {
        'course_id': 17,
        'course_name': 'AI Tools Basic',
        'course_slug': 'ai-tools-basic',
        'allusers_path': '/aitb/users',
        'user_path': '/aitb/user/{userid}',
        'certificates_requested_path': '/aitb/certificates-requested',
        'certificates_generated_path': '/aitb/certificates-generated',
        'generate_certificate_path': '/aitb/user/{userid}/generate-certificate',
        'certificate_bucket': 'aitb-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/aitools_basic_blank_certificate.png'
    },
    'aita': {
        'course_id': 18,
        'course_name': 'AI Tools Advanced',
        'course_slug': 'ai-tools-advanced',
        'allusers_path': '/aita/users',
        'user_path': '/aita/user/{userid}',
        'certificates_requested_path': '/aita/certificates-requested',
        'certificates_generated_path': '/aita/certificates-generated',
        'generate_certificate_path': '/aita/user/{userid}/generate-certificate',
        'certificate_bucket': 'aita-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/aitools_advanced_blank_certificate.png'
    },
    'mindm': {
        'course_id': 19,
        'course_name': 'Mind Management',
        'course_slug': 'mind-management',
        'allusers_path': '/mindm/users',
        'user_path': '/mindm/user/{userid}',
        'certificates_requested_path': '/mindm/certificates-requested',
        'certificates_generated_path': '/mindm/certificates-generated',
        'generate_certificate_path': '/mindm/user/{userid}/generate-certificate',
        'certificate_bucket': 'mindm-certificate-bucket',
        'levels': 11,
        'blank_certificate_location': 'certificate_format/mind_management_blank_certificate.png'
    }
}

