suggested_commands = {
    'start': 'the beginning',
    'methodology': 'read about our methodology',
    'howtohomework': 'read how to submit homework',
    'part1': 'start part 1',
    'part2': 'start part 2',
    'part3': 'start part 3',
    'part4': 'start part 4',
    'part5': 'start part 5',
    'part6': 'start part 6',
    'part7': 'start part 7',
    'part8': 'start part 8',
    'mycourses': 'check all your courses',
    'myhomework': 'check your homework links',
    'myquestions': 'check your questions',
    'register': 'one time registration',
    'editprofile': 'edit name or email',
    'question': 'ask question to mentor',
    'donate': 'learn benefits of donation',
    'discord': 'discord link',
    'telegramgroup': 'telegram group link',
    'community': 'links to join our community',
    # 'unlock': 'unlock paid version (from lesson 11)',
    # 'whybuyme': 'why you should buy me',
    'certificate': 'request certificate (on completion)',
    'changelog': 'view changelog',
    'outline': 'outline of this course',
    'allcourses': 'know details of cto-track',
    'jobroles': 'roles u can apply for on completion',
    'myreferrals': 'see how many ppl used your referral code',
    'part9': 'start part 9',
    'part10': 'start part 10',
    'part11': 'start part 11',
    'part12': 'start part 12',
     'part13': 'start part 13',
     'part14': 'start part 14',
     'part15': 'start part 15',
     'part16': 'start part 16',
     'part17': 'start part 17',
     'part18': 'start part 18',
     'part19': 'start part 19',
}